server:
  port: 8080
  servlet:
    context-path: /ejile

spring:
  datasource:
    url: jdbc:mysql://mysql-api:3306/ejile?&serverTimezone=Asia/Shanghai
    username: ejile
    password: b*&!@NKD1654489
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 10000
      maximum-pool-size: 10
      minimum-idle: 3
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  redis:
    host: redis-api
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
